<?php require_once "includes/conexion.php";
$Cabecera = array(
    "id_tipo_equipo" => "string",
    "id_estado" => "string",
    "id_contacto" => 0,
    "telefono_contacto" => "string",
    "numero_serial_interno" => "string",
    "numero_serial_fabricante" => "string",
    "id_articulo" => "string",
    "articulo" => "string",
    "id_socio_negocio" => "string",
    "socio_negocio" => "string",
    "direccion" => "string",
    "id_postal" => "string",
    "barrio" => "string",
    "distrito" => "string",
    "ciudad" => "string",
    "id_pais" => "string",
    "id_territorio" => 0,
    "id_tecnico_responsable" => 0,
    "id_anexo" => 0,
    "id_doc_portal" => "string",
    "usuario_creacion" => "string",
    "CDU_id_marca" => "string",
    "CDU_id_linea" => "string",
    "CDU_annio" => "string",
    "CDU_id_concesionario" => "string",
    "CDU_id_color" => "string",
    "CDU_id_cilindraje" => "string",
    "CDU_id_tipo_servicio" => "string",
    "CDU_fecha_matricula" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_tecnicomecanica" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_soat" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_ult_cambio_aceite" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_ult_mantenimiento" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_ult_cambio_llanta" => "2022-01-31T13:39:21.615Z",
    "CDU_fecha_ult_alineacion_balanceo" => "2022-01-31T13:39:21.615Z",
    "anexos" => array(
        array(
            "id_anexo" => 0,
            "tipo_documento" => 0,
            "id_documento" => 0,
            "archivo" => "string",
            "ext_archivo" => "string",
            "metodo" => 0,
            "fecha" => "2022-01-31T13:39:21.615Z",
            "id_usuario" => 0,
            "comentarios" => "string",
            "id_destino_evidencia" => "string",
        ),
        array(
            "id_anexo" => 0,
            "tipo_documento" => 0,
            "id_documento" => 0,
            "archivo" => "string",
            "ext_archivo" => "string",
            "metodo" => 0,
            "fecha" => "2022-01-31T13:39:21.615Z",
            "id_usuario" => 0,
            "comentarios" => "string",
            "id_destino_evidencia" => "string",
        ),
    ),
);
$Metodo = "TarjetaEquipos";
$Resultado = EnviarWebServiceSAP($Metodo, $Cabecera, true, true);
